# Generated by Django 4.2.5 on 2023-09-08 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='ANS',
            new_name='test_text',
        ),
    ]
